### ISSUE TITLE
TDD CheckList

### ISSUE THREAD

**Issue by thaomonster** [thaomonster/travel-tracker#8]
As a developer,

When I create a class file,

I want to 
- [x] to create a test file
- [x] test class default properties
- [x] class methods
- [x] anything that updates class properties
- [x] create a separate test-data folder to hold a smaller version of the data to test,

So that other developers can use the test as a faster way to test whether your functions are working correctly.
